openapi: 3.0.3
info:
  description: Swagger LMS CMS - OpenAPI 3.0.
  title: Swagger LMS CMS - OpenAPI 3.0
  version: 1.0.0
servers:
  - url: https://laravel-quan-ly-diem-ren-luyen.vercel.app/api
  - url: http://127.0.0.1:8000/api
paths:
  /auth/login:
    post:
      summary: Đăng nhập người dùng
      description: Xác thực người dùng bằng email và mật khẩu
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  example: "123456"
      responses:
        "200":
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "User login successfully."
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI..."
                      token_type:
                        type: string
                        example: "bearer"
                      expires_in:
                        type: integer
                        example: 3600
        "401":
          description: Sai thông tin đăng nhập

  /auth/logout:
    post:
      summary: Đăng xuất người dùng
      description: Hủy token xác thực hiện tại
      operationId: logoutUser
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Đăng xuất thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Successfully logged out."

  /auth/profile:
    get:
      summary: Lấy thông tin người dùng
      description: Lấy thông tin tài khoản đã xác thực
      operationId: getUserProfile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lấy thông tin thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "User profile retrieved successfully."
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: "Nguyen Van A"
                      email:
                        type: string
                        example: "user@example.com"

  /auth/refresh:
    post:
      summary: Làm mới token
      description: Tạo lại token xác thực mới
      operationId: refreshToken
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Token mới được cấp
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Refresh token return successfully."
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI..."
                      token_type:
                        type: string
                        example: "bearer"
                      expires_in:
                        type: integer
                        example: 3600
