preset: laravel
risky: false
version: 8.3
monolithic: true
finder:
  exclude:
    - "modules"
    - "node_modules"
    - "nova"
    - "nova-components"
    - "storage"
    - "spark"
    - "vendor"
  name: "*.php"
  not-name:
    - "_ide_helper.php"
