name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      path_to_repo:
        required: true
        type: string
      deploy_url:
        required: true
        type: string
      ssh_user: 
        required: true
        type: string
      ssh_host: 
        required: true
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, vps]
    environment: ${{ inputs.environment }}
    env:
      PATH_TO_REPO: ${{ inputs.path_to_repo }}
      ENVIRONMENT: ${{ inputs.environment }}
      DEPLOY_URL: ${{ inputs.deploy_url }}
      SSH_USER: ${{ inputs.ssh_user }}
      SSH_VPS_HOST: ${{ inputs.ssh_host }}
      GITHUB_TOKEN: ${{ inputs.github_token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Không cần khai báo trong secrets workflow_call

      - name: Determine branch/tag
        id: specify-ref
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            REF=${{ github.ref_name }}
          else
            REF="main"
          fi
          echo "REF=$REF" >> $GITHUB_ENV

      - name: SSH into server and deploy
        env:
          SSH: ssh -T root@vps.mrkiet.name.vn
        run: |
          ${{ env.SSH }} git -C ${{ env.PATH_TO_REPO }} fetch --all
          ${{ env.SSH }} git -C ${{ env.PATH_TO_REPO }} checkout --force ${{ steps.specify-ref.outputs.REF }}
          ${{ env.SSH }} git -C ${{ env.PATH_TO_REPO }} pull

      - name: Mark Deployment as Successful
        if: success()
        run: |
          curl -X POST -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/deployments/${{ env.DEPLOYMENT_ID }}/statuses \
               -d '{
                    "state": "success",
                    "description": "✅ ${{ env.ENVIRONMENT }} Deploy Success",
                    "environment_url": "${{ env.DEPLOY_URL }}"
                  }'

      - name: Mark Deployment as Failed
        if: failure()
        run: |
          curl -X POST -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/deployments/${{ env.DEPLOYMENT_ID }}/statuses \
               -d '{
                    "state": "failure",
                    "description": "❌ ${{ env.ENVIRONMENT }} Deploy Failed"
                  }'
