name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      path_to_repo:
        required: true
        type: string
      environment_url:
        required: false
        type: string
    secrets:
      SSH_USER:
        required: true
      SSH_VPS_HOST:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, ansible]
    environment: ${{ inputs.environment }}
    env:
      PATH_TO_REPO: ${{ inputs.path_to_repo }}
      ENVIRONMENT: ${{ inputs.environment }}
      ENVIRONMENT_URL: ${{ inputs.environment_url }}

    steps:
      - name: Clone repository
        run: |
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_VPS_HOST }} << EOF
            set -e
            if [ ! -d "${{ env.PATH_TO_REPO }}/.git" ]; then
              echo "Cloning repository..."
              git clone git@github.com:${{ github.repository }}.git ${{ env.PATH_TO_REPO }}
            fi
            cd ${{ env.PATH_TO_REPO }}
            git pull origin main
          EOF
