name: Preview Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Preview
      path_to_repo: ${{ secrets.PATH_TO_REPO }}
      deploy_url: ${{ secrets.DEPLOY_URL }}
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_host: ${{ secrets.SSH_VPS_HOST }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
